[package]
authors = ["Walther Chen <walther.chen@gmail.com>", "Jay Majithia <jayrmajithia@gmail.com>"]
name = "acs-explorer"
version = "0.5.0"

[dependencies]
reqwest="0.9.22"
json="0.12.0"
structopt="0.3.4"
error-chain="0.12.1"
